### ISSUE TITLE
Running Iked 

### ISSUE THREAD

**Issue by musaleh17** [openiked/openiked-portable#100]
Hi,

I am wondering if there is any guide for how to run IKED between two peers somewhere including creating the conf file, ikectl commands, ..., or if there is any demo?

**Comment by tobhe** [comment]
There isn't any demo but this [manual](https://www.openbsd.org/faq/faq17.html#server) should help you get the configuration right. After you have set up the configuration you should be able to run the daemon with `iked -d` to see if it works as intended (-d to run in the foreground and log to stdout).

**Comment by musaleh17** [comment]
great thanks,

I want to verify something when creating the SA for IKE phase 1, XFRM the kernel transforming configuration layer is used for encryption of the payload, right? 


and In phase 2, only pfkey is used for updating the SAD SPD tables in the kernel, right? 

did I miss any details?

**Comment by tobhe** [comment]
Phase 1 (or the IKE SA in ikev2 terminology) does not interact with the kernel at all, packets are sent from user land and encrypted via OpenSSL API.  Phase 2 (Child SA) is handled by the kernel. We don't currently use xfrm but the older pfkey interface to pass these options to the kernel, but you can view them via `ip xfrm s` and `ip xfrm p`.

**Comment by musaleh17** [comment]
Then the appearance of XFRM in ikev2_pld.c is an internal implementation and doesn't rely on the Kernel module?

**Comment by tobhe** [comment]
xfrm is used there as abbreviation for the word transform and was probably adopted from the RFC. This has nothing to do with the linux xfrm subsystem as in netlink-xfrm.
