### ISSUE TITLE
when I run iked on ubuntu20, I meet a problem.  "control: proc_run: chroot: No such file or directory      ikev2: proc_run: chroot: No such file or directory".   what happened?

### ISSUE THREAD

**Issue by bin-wang1** [openiked/openiked-portable#104]
bennie@ubuntu:~/Desktop$ sudo iked -dv
control: proc_run: chroot: No such file or directory
ikev2: proc_run: chroot: No such file or directory
ikev2 "server2_rsa" active tunnel esp inet from 192.168.40.133/32 to 192.168.40.132/32 local any peer 192.168.40.132 ikesa enc aes-128-gcm enc aes-256-gcm prf hmac-sha2-256 prf hmac-sha2-384 prf hmac-sha2-512 prf hmac-sha1 group curve25519 group ecp521 group ecp384 group ecp256 group modp4096 group modp3072 group modp2048 group modp1536 group modp1024 ikesa enc aes-256 enc aes-192 enc aes-128 enc 3des prf hmac-sha2-256 prf hmac-sha2-384 prf hmac-sha2-512 prf hmac-sha1 auth hmac-sha2-256 auth hmac-sha2-384 auth hmac-sha2-512 auth hmac-sha1 group curve25519 group ecp521 group ecp384 group ecp256 group modp4096 group modp3072 group modp2048 group modp1536 group modp1024 childsa enc aes-256 enc aes-192 enc aes-128 auth hmac-sha2-384 auth hmac-sha2-512 auth hmac-sha1 group none noesn srcid client.wb.com lifetime 10800 bytes 4294967296 signature
lost child: ikev2 exited abnormally
ca exiting, pid 7143
parent terminating

**Comment by tobhe** [comment]
Have you installed iked via apt or built it from source? It looks like you are missing `/var/empty` which the unprivileged processes chroot to to hide the file system. `mkdir /var/empty` should fix that.

**Comment by bin-wang1** [comment]
Thanks! the problem is solved.  you are right, I built iked from source. thank you again!
