### ISSUE TITLE
Ｉ　ｈａｖｅ　ａ　ｑｕｅｓｔｉｏｎ．

### ISSUE THREAD

**Issue by bin-wang1** [openiked/openiked-portable#105]
Friend, I want to use other algorithms instead of RSA for public key authentication. What should I do? Or can I replace the RSA algorithm directly with my own algorithm in the code.

**Comment by tobhe** [comment]
You won't need to replace anything. To use EC keys just generate a new key pair like:
```
openssl ecparam -genkey -name prime256v1 -noout -out /etc/iked/private/local.key
openssl ec -in "/etc/iked/private/local.key" -pubout -out /etc/iked/local.pub
```
If you leave the ikeauth config option empty (no psk etc) that will be used by default.

**Comment by bin-wang1** [comment]
Thank you very much

**Comment by bin-wang1** [comment]
> You won't need to replace anything. To use EC keys just generate a new key pair like:
> 
> ```
> openssl ecparam -genkey -name prime256v1 -noout -out /etc/iked/private/local.key
> openssl ec -in "/etc/iked/private/local.key" -pubout -out /etc/iked/local.pub
> ```
> 
> If you leave the ikeauth config option empty (no psk etc) that will be used by default.

Can it be understood that iked is calling openSSL to achieve encryption and decryption. Therefore, as long as it is a public key cryptographic algorithm supported by OpenSSL, we can use it for public key authentication？

**Comment by bin-wang1** [comment]
Thank you very much. you are a good person!
