### ISSUE TITLE
I'm having a problem. When I create a CA with iketcl, I am reminded that the file is missing. Thanks

### ISSUE THREAD

**Issue by bin-wang1** [openiked/openiked-portable#106]
bennie@client:/etc/iked$ sudo ikectl ca vpn create
CA passphrase:
Retype CA passphrase:
Generating RSA private key, 2048 bit long modulus (2 primes)
............................................+++++
................+++++
e is 65537 (0x010001)
ikectl: fopen /etc/ssl/x509v3.cnf: No such file or directory

**Comment by bin-wang1** [comment]
How can I get x509v3.cnf？

**Comment by tobhe** [comment]
Thanks for the report, should be fixed with the latest commit. We didn't ship the config file because that is normally included with libressl. When building with openssl we need to ship our own.
