### ISSUE TITLE
Hello, guys. I'm a newbie. I want to write code for ESP to work with openiked. But I can't find the SA generated by IKE, where is the SA stored? Thank you,  brothers

### ISSUE THREAD

**Issue by bin-wang1** [openiked/openiked-portable#108]
Hello, guys. I'm a newbie. I want to write code for ESP to work with openiked. But I can't find the SA generated by IKE, where is the SA stored?

**Comment by tobhe** [comment]
Hi, I'm not sure how I can help you here. The ESP SA is stored in the kernel, so the tooling depends on what operating system you are using. On linux for example you could view the SAs with `ip xfrm state` and the policies with `ip xfrm policy` (see `man ip-xfrm`)

**Comment by bin-wang1** [comment]
thank you very much&nbsp;


王斌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tobias ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 晚上11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [openiked/openiked-portable] Hello, guys. I&#39;m a newbie. I want to write code for ESP to work with openiked. But I can&#39;t find the SA generated by IKE, where is the SA stored? Thank you,  brothers (Issue #108)





 
Hi, I'm not sure how I can help you here. The ESP SA is stored in the kernel, so the tooling depends on what operating system you are using. On linux for example you could view the SAs with ip xfrm state and the policies with ip xfrm policy (see man ip-xfrm)
