### ISSUE TITLE
ikectl should safely handle existing certificates

### ISSUE THREAD

**Issue by ryanakca** [openiked/openiked-portable#125]
The command `ikectl ca ... certificate ... create` should check if the certificate already exists, and handle them safely if so.

Currently, if a certificate already exists, then ikectl complains the certificate already exists, replaces it by an empty file, and then prints an error messages whenever you try to run ca-related commands: `9694781920320:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/usr/src/lib/libcrypto/pem/pem_lib.c:694:Expecting: TRUSTED CERTIFICATE`

It is difficult to recover from this inconsistent state. Indeed, deleting the certificate with `ikectl` does not fix the inconsistent state. For example, after running `ikectl ca vpn certificate test create` twice and then `ikectl ca vpn certificate test delete`, the inconsistent state persists:

```
<rak@hades:/home/rak:5021>$ doas ikectl show ca vpn certificate test
ikectl: could not open file test.crt: No such file or directory
<rak@hades:/home/rak:5022>$ doas ikectl ca vpn certificate test create
Generating RSA private key, 2048 bit long modulus
...................
......................................................
e is 65537 (0x010001)
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg, fully qualified host name) [test]:
Using configuration from /etc/ssl/vpn/test-ssl.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'test'
ERROR:There is already a certificate for /CN=test
The matching entry has the following details
Type      :Valid
Expires on    :240928132847Z
Serial Number :1F
File name     :unknown
Subject Name  :/CN=test
<rak@hades:/home/rak:5023>$ doas ikectl show ca vpn certificate test
unable to load certificate
6762873799744:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/usr/src/lib/libcrypto/pem/pem_lib.c:694:Expecting: TRUSTED CERTIFICATE

<rak@hades:/home/rak:5024>$ ls -lash /etc/ssl/vpn/test.crt
0 -rw-r--r--  1 root  wheel     0B Sep 29 09:38 /etc/ssl/vpn/test.crt
```

I get bit by this bug annually when renewing expired certificates. Perhaps we could document in ikectl(8) the steps to take for renewing an expired certificate?

**Comment by tobhe** [comment]
Finally had some time to take a look and I think I figured it out.

The reason this fails is that the ca has `unique_subject` set to `yes` which causes the Error in your log. I can fix it upstream by modifying ikeca.cnf which will work for all future CAs.

Since you probably want to reuse your already existing CA you will need to fix that by hand. In `/etc/ssl/$CANAME/index.txt.attr` change `unique_subject = yes` to `unique_subject = no`. This fixed the issue for me.

**Comment by tobhe** [comment]
For added context OpenSSL says that `unique_subject = no` [should be the default](https://github.com/openssl/openssl/issues/5451). The [man page](https://www.openssl.org/docs/man1.1.1/man1/openssl-ca.html) also acknowledges the renewal problem you were seeing:

> The default value is yes, to be compatible with older (pre 0.9.8) versions of OpenSSL. However, to make CA certificate roll-over easier, it's recommended to use the value no, especially if combined with the -selfsign command line option.

**Comment by tobhe** [comment]
Closing because the fix has landed in OpenBSD and -portable.
