### ISSUE TITLE
rekeying issue when exceeding 'bytes' limit (500MB)

### ISSUE THREAD

**Issue by tub5ta** [openiked/openiked-portable#72]
Doing throughput testing on FreeBSD, an issue developed where rekeying after the default 500MB breaks iked_activesas/sa_childsas. By setting lifetime and bytes to 0 (bad), there are no rekeying issues. If the daemon is restarted on the active side, sas are re-established until limits are hit again.

root@host2:~ # iperf3 -c 10.104.0.2 -t 60
Connecting to host 10.104.0.2, port 5201
[  5] local 10.104.0.3 port 34993 connected to 10.104.0.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   184 MBytes  1.54 Gbits/sec  218    482 KBytes
[  5]   1.00-2.00   sec   184 MBytes  1.55 Gbits/sec  327    587 KBytes
[  5]   2.00-3.01   sec   182 MBytes  1.52 Gbits/sec  404    451 KBytes
[  5]   3.01-4.07   sec  0.00 Bytes  0.00 bits/sec    6   1.41 KBytes
[  5]   4.07-5.07   sec  0.00 Bytes  0.00 bits/sec    4   1.41 KBytes

Pre-test established connection:

root@host2:~ # ikectl sho sa
iked_sas: 0x800e8d700 rspi 0x0987dc3611f1eb76 ispi 0x304d3387ad836aa7 10.104.0.3:500->10.104.0.2:500<FQDN/host1.domain.net>[] ESTABLISHED i nexti 0x0 pol 0x800e5b000
  sa_childsas: 0x800e30600 ESP 0xcebf1004 out 10.104.0.3:500 -> 10.104.0.2:500 (L) B=0x0 P=0x800e30540 @0x800e8d700
  sa_childsas: 0x800e30540 ESP 0xe1742fb8 in 10.104.0.2:500 -> 10.104.0.3:500 (LA) B=0x0 P=0x800e30600 @0x800e8d700
  sa_flows: 0x800e80280 ESP out 10.104.0.3/32 -> 10.104.0.2/32 [0]@-1 (L) @0x800e8d700
  sa_flows: 0x800e80780 ESP in 10.104.0.2/32 -> 10.104.0.3/32 [0]@-1 (L) @0x800e8d700
iked_activesas: 0x800e30600 ESP 0xcebf1004 out 10.104.0.3:500 -> 10.104.0.2:500 (L) B=0x0 P=0x800e30540 @0x800e8d700
iked_activesas: 0x800e30540 ESP 0xe1742fb8 in 10.104.0.2:500 -> 10.104.0.3:500 (LA) B=0x0 P=0x800e30600 @0x800e8d700
iked_flows: 0x800e80780 ESP in 10.104.0.2/32 -> 10.104.0.3/32 [0]@-1 (L) @0x800e8d700
iked_flows: 0x800e80280 ESP out 10.104.0.3/32 -> 10.104.0.2/32 [0]@-1 (L) @0x800e8d700
iked_dstid_sas: 0x800e8d700 rspi 0x0987dc3611f1eb76 ispi 0x304d3387ad836aa7 10.104.0.3:500->10.104.0.2:500<FQDN/host1.domain.net>[] ESTABLISHED i nexti 0x0 pol 0x800e5b000

When limits exceeded:

root@host2:~ # ikectl sho sa
iked_sas: 0x800e8d700 rspi 0x0987dc3611f1eb76 ispi 0x304d3387ad836aa7 10.104.0.3:500->10.104.0.2:500<FQDN/host1.domain.net>[] ESTABLISHED i nexti 0x0 pol 0x800e5b000
  sa_flows: 0x800e80280 ESP out 10.104.0.3/32 -> 10.104.0.2/32 [0]@-1 (L) @0x800e8d700
  sa_flows: 0x800e80780 ESP in 10.104.0.2/32 -> 10.104.0.3/32 [0]@-1 (L) @0x800e8d700
iked_flows: 0x800e80780 ESP in 10.104.0.2/32 -> 10.104.0.3/32 [0]@-1 (L) @0x800e8d700
iked_flows: 0x800e80280 ESP out 10.104.0.3/32 -> 10.104.0.2/32 [0]@-1 (L) @0x800e8d700
iked_dstid_sas: 0x800e8d700 rspi 0x0987dc3611f1eb76 ispi 0x304d3387ad836aa7 10.104.0.3:500->10.104.0.2:500<FQDN/host1.domain.net>[] ESTABLISHED i nexti 0x0 pol 0x800e5b000

**Comment by tub5ta** [comment]
If the rate backs off, throughput lasts longer for some reason but in the end the childsa still dies:

[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-53.19  sec  1.76 GBytes   285 Mbits/sec   16             sender
[  5]   0.00-53.19  sec  0.00 Bytes  0.00 bits/sec                  receiver

**Comment by tobhe** [comment]
Thanks for the report, I managed to confirm and reproduce the issue.  Looks like the old Child SAs are deleted without Child SA rekeying being triggered. I'll see if i can come up with a fix.

**Comment by tobhe** [comment]
Can you also share your iked log from when the Child SAs are deleted? Do you see any CREATE_CHILD_SA messages in your log?

**Comment by tub5ta** [comment]
Here is a full cycle in the test phase:

Jun  6 07:42:54 ip2 iked[18026]: ikev2_init_ike_sa: initiating "policy1"
Jun  6 07:42:54 ip2 iked[18026]: spi=0xa51ee4a19e49248a: send IKE_SA_INIT req 0 peer 192.168.1.1:500 local 192.168.1.2:500, 502 bytes
Jun  6 07:42:54 ip2 iked[18026]: spi=0xa51ee4a19e49248a: recv IKE_SA_INIT res 0 peer 192.168.1.1:500 local 192.168.1.2:500, 219 bytes, policy 'policy1'
Jun  6 07:42:54 ip2 iked[18026]: spi=0xa51ee4a19e49248a: send IKE_AUTH req 1 peer 192.168.1.1:500 local 192.168.1.2:500, 475 bytes
Jun  6 07:42:54 ip2 iked[18026]: spi=0xa51ee4a19e49248a: recv IKE_AUTH res 1 peer 192.168.1.1:500 local 192.168.1.2:500, 355 bytes, policy 'policy1'
Jun  6 07:42:54 ip2 iked[18026]: spi=0xa51ee4a19e49248a: ikev2_childsa_enable: loaded SPIs: 0xa0d68be5, 0xc00d3fb4 (enc aes-128-gcm esn)
Jun  6 07:42:54 ip2 iked[18026]: spi=0xa51ee4a19e49248a: ikev2_childsa_enable: loaded flows: ESP-192.168.1.2/32=192.168.1.1/32(0)
Jun  6 07:42:54 ip2 iked[18026]: spi=0xa51ee4a19e49248a: established peer 192.168.1.1:500[FQDN/ip1.example.com] local 192.168.1.2:500[FQDN/ip2.example.com] policy 'policy1' as initiator (enc aes-128-gcm group curve25519 prf hmac-sha2-256)
Jun  6 07:43:16 ip2 iked[18026]: spi=0xa51ee4a19e49248a: recv CREATE_CHILD_SA req 0 peer 192.168.1.1:500 local 192.168.1.2:500, 305 bytes, policy 'policy1'
Jun  6 07:43:16 ip2 iked[18026]: spi=0xa51ee4a19e49248a: send CREATE_CHILD_SA res 0 peer 192.168.1.1:500 local 192.168.1.2:500, 177 bytes
Jun  6 07:43:16 ip2 iked[18026]: spi=0xa51ee4a19e49248a: ikev2_childsa_enable: loaded SPIs: 0x29cdab79, 0x46238853 (enc aes-128-gcm esn)
Jun  6 07:43:16 ip2 iked[18026]: spi=0xa51ee4a19e49248a: deleted 1 SPI: 0xa0d68be5
Jun  6 07:43:27 ip2 iked[18026]: spi=0xa51ee4a19e49248a: recv CREATE_CHILD_SA req 2 peer 192.168.1.1:500 local 192.168.1.2:500, 305 bytes, policy 'policy1'
Jun  6 07:43:27 ip2 iked[18026]: spi=0xa51ee4a19e49248a: send CREATE_CHILD_SA res 2 peer 192.168.1.1:500 local 192.168.1.2:500, 177 bytes
Jun  6 07:43:27 ip2 iked[18026]: spi=0xa51ee4a19e49248a: ikev2_childsa_enable: loaded SPIs: 0xd67b066b, 0x9ba7a95b (enc aes-128-gcm esn)
Jun  6 07:43:27 ip2 iked[18026]: spi=0xa51ee4a19e49248a: deleted 1 SPI: 0x46238853
Jun  6 07:43:37 ip2 iked[18026]: spi=0xa51ee4a19e49248a: recv CREATE_CHILD_SA req 4 peer 192.168.1.1:500 local 192.168.1.2:500, 305 bytes, policy 'policy1'
Jun  6 07:43:37 ip2 iked[18026]: spi=0xa51ee4a19e49248a: send CREATE_CHILD_SA res 4 peer 192.168.1.1:500 local 192.168.1.2:500, 177 bytes
Jun  6 07:43:37 ip2 iked[18026]: spi=0xa51ee4a19e49248a: ikev2_childsa_enable: loaded SPIs: 0xeede149f, 0x34a7a45b (enc aes-128-gcm esn)
Jun  6 07:43:37 ip2 iked[18026]: spi=0xa51ee4a19e49248a: deleted 1 SPI: 0x9ba7a95b
Jun  6 07:43:48 ip2 iked[18026]: spi=0xa51ee4a19e49248a: send CREATE_CHILD_SA req 2 peer 192.168.1.1:500 local 192.168.1.2:500, 305 bytes
Jun  6 07:43:48 ip2 iked[18026]: spi=0xa51ee4a19e49248a: deleted 1 SPI: 0x34a7a45b
Jun  6 07:43:48 ip2 iked[18026]: spi=0xa51ee4a19e49248a: recv CREATE_CHILD_SA res 2 peer 192.168.1.1:500 local 192.168.1.2:500, 69 bytes, policy 'policy1'
Jun  6 07:43:48 ip2 iked[18026]: ikev2_child_sa_acquire: flow wasn't found
Jun  6 07:44:46 ip2 syslogd: last message repeated 1 times
Jun  6 07:44:50 ip2 syslogd: last message repeated 1 times
Jun  6 07:44:53 ip2 ntpd[76037]: adjusting local clock by 0.704818s
Jun  6 07:45:24 ip2 iked[18026]: ikev2_child_sa_acquire: flow wasn't found
Jun  6 07:45:50 ip2 syslogd: last message repeated 1 times
Jun  6 07:47:48 ip2 syslogd: last message repeated 3 times
Jun  6 11:33:27 ip2 iked[18026]: spi=0xa51ee4a19e49248a: ikev2_ikesa_recv_delete: received delete
Jun  6 11:33:27 ip2 iked[18026]: spi=0xa51ee4a19e49248a: sa_free: received delete
Jun  6 11:33:33 ip2 iked[17242]: parent_sig_handler: stopping iked
Jun  6 11:33:33 ip2 iked[18026]: ikev2 exiting, pid 18026
Jun  6 11:33:33 ip2 iked[17551]: ca exiting, pid 17551
Jun  6 11:33:33 ip2 iked[17721]: control exiting, pid 17721
Jun  6 11:33:33 ip2 iked[17242]: parent terminating
Jun  6 11:34:10 ip2 iked[81959]: ikev2_init_ike_sa: initiating "policy1"
Jun  6 11:34:10 ip2 iked[81959]: spi=0xe114aaa28779f31f: send IKE_SA_INIT req 0 peer 192.168.1.1:500 local 192.168.1.2:500, 502 bytes
Jun  6 11:34:10 ip2 iked[81959]: spi=0xe114aaa28779f31f: recv IKE_SA_INIT res 0 peer 192.168.1.1:500 local 192.168.1.2:500, 219 bytes, policy 'policy1'
Jun  6 11:34:10 ip2 iked[81959]: spi=0xe114aaa28779f31f: send IKE_AUTH req 1 peer 192.168.1.1:500 local 192.168.1.2:500, 476 bytes
Jun  6 11:34:10 ip2 iked[81959]: spi=0xe114aaa28779f31f: recv IKE_AUTH res 1 peer 192.168.1.1:500 local 192.168.1.2:500, 353 bytes, policy 'policy1'
Jun  6 11:34:10 ip2 iked[81959]: spi=0xe114aaa28779f31f: ikev2_childsa_enable: loaded SPIs: 0xef17a2aa, 0xa671038f (enc aes-128-gcm esn)

**Comment by tub5ta** [comment]
Testing on two different hosts:

root@ike02:~ # iperf3 -c 10.104.0.2 -t 600
Connecting to host 10.104.0.2, port 5201
[  5] local 10.104.0.3 port 56598 connected to 10.104.0.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   210 MBytes  1.76 Gbits/sec    0    781 KBytes
[  5]   1.00-2.00   sec   178 MBytes  1.49 Gbits/sec  872    360 KBytes
[  5]   2.00-3.01   sec   213 MBytes  1.78 Gbits/sec    0    867 KBytes
[  5]   3.01-4.07   sec  0.00 Bytes  0.00 bits/sec    6   1.41 KBytes
[  5]   4.07-5.07   sec  0.00 Bytes  0.00 bits/sec    4   1.41 KBytes
[  5]   5.07-6.07   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes

------

Jun 16 00:13:40 ike02 iked[1249]: ikev2_init_ike_sa: initiating "policy1"
Jun 16 00:13:40 ike02 iked[1249]: spi=0x9fd13573ebd8236e: send IKE_SA_INIT req 0 peer 10.104.0.2:500 local 10.104.0.3:500, 502 bytes
Jun 16 00:13:40 ike02 iked[1249]: spi=0x9fd13573ebd8236e: recv IKE_SA_INIT res 0 peer 10.104.0.2:500 local 10.104.0.3:500, 219 bytes, policy 'policy1'
Jun 16 00:13:40 ike02 iked[1249]: spi=0x9fd13573ebd8236e: send IKE_AUTH req 1 peer 10.104.0.2:500 local 10.104.0.3:500, 471 bytes
Jun 16 00:13:40 ike02 iked[1249]: spi=0x9fd13573ebd8236e: recv IKE_AUTH res 1 peer 10.104.0.2:500 local 10.104.0.3:500, 350 bytes, policy 'policy1'
Jun 16 00:13:40 ike02 iked[1249]: spi=0x9fd13573ebd8236e: ikev2_childsa_enable: loaded SPIs: 0xb5f507f3, 0xb76081a0 (enc aes-128-gcm esn)
Jun 16 00:13:40 ike02 iked[1249]: spi=0x9fd13573ebd8236e: ikev2_childsa_enable: loaded flows: ESP-10.104.0.3/32=10.104.0.2/32(0)
Jun 16 00:13:40 ike02 iked[1249]: spi=0x9fd13573ebd8236e: established peer 10.104.0.2:500[FQDN/ike01.example.com] local 10.104.0.3:500[FQDN/ike02.example.com] policy 'policy1' as initiator (enc aes-128-gcm group curve25519 prf hmac-sha2-256)
Jun 16 00:13:59 ike02 iked[1249]: ikev2_child_sa_acquire: flow wasn't found
Jun 16 00:14:03 ike02 syslogd: last message repeated 13 times

**Comment by tobhe** [comment]
I think the main issue here is really just the default of 500 MB being too low for your throughput. I noticed that FreeBSD won't send a soft lifetime pfkey message when the limit is reached too fast, causing the SA to be deleted without a chance to rekey.

There is a second issue here, which is that acquire can't find the matching flow. Acquire should trigger a reconnect for the missing SAs, which would slow down your connection but prevent a full stop. You don't really want to run into this case, but it surely is better than loosing your connection.

In your case the best solution would be to crank up the bytes limit to something closer to 5 GB. We should also consider increasing the default. 500 MB does seem a little conservative. Looking at the *swans it seems like they don't set any byte limits by default.

**Comment by tub5ta** [comment]
5GB would be a sane change today, especially as bandwidth is larger. Below are tests with 'lifetime 3h bytes 5g' and no issues of rekeying through extensive testing:

Receive:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-1800.00 sec   339 GBytes  1.62 Gbits/sec  724232             sender
[  5]   0.00-1800.00 sec   339 GBytes  1.62 Gbits/sec                  receiver

Send:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-1800.00 sec   358 GBytes  1.71 Gbits/sec  1370200             sender
[  5]   0.00-1800.01 sec   358 GBytes  1.71 Gbits/sec                  receiver

The above saw ~42% host CPU utilisation on the host.

I'll test the above commit and advise if I hit any further issues.  Thanks for addressing this.

**Comment by tobhe** [comment]
Just a small update: after some discussion over at tech@ we changed the default to 4 GB which should work a lot better
