### ISSUE TITLE
Openiked as keying daemon only 

### ISSUE THREAD

**Issue by musaleh17** [openiked/openiked-portable#99]
Hi, 

I am wondering if I can use Openiked without doing any IPSEC flows, in other words I want to use Openiked to run IKE protocol only,
and getting the SAs on both hosts. 

what do you think at can be used for SAs creation only and they would be accessible by the user?

**Comment by tobhe** [comment]
I don't think it is currently possible to configure it that way without hacks. Can you give a little more detail about how your use-case would look like? If iked doesn't manage the flows, where would they come from instead? Can you point me to another IKE implementation supporting this?

**Comment by musaleh17** [comment]
I have an application that can do the IPSEC flows and managed them, the missing section on my side is the secured negotiation between the two hosts to have a shared key, I am looking for an external keying daemon that I can use to create SA on use space (IKE protocol) and attach them to my application. 

I found another open source where you can add a plugin to the daemon and your plugin will be loaded and it will manage the SAs, and policies against external IPSEC applications. 
does the Openiked project support such a similar feature? or I can store locally on my device the result of the IKE protocol or print them without doing any IPSEC policies?

**Comment by tobhe** [comment]
> I found another open source where you can add a plugin to the daemon and your plugin will be loaded and it will manage the SAs, and policies against external IPSEC applications.
does the Openiked project support such a similar feature?

no, there is no plugin support. It either is part of the main code base or it is not supported. 

> or I can store locally on my device the result of the IKE protocol or print them without doing any IPSEC policies?

I'm afraid that is not currently possible with OpenIKED.

Maybe [strongswan](https://github.com/strongswan/strongswan) or [libreswan](https://github.com/libreswan/libreswan) are better suited for your use-case but I am not sure if any of them support what you are trying to achieve. If you aren't afraid to touch c code you could of course try patching the code yourself.
